app/views/doc_.py
from flask import Blueprint, redirect, render_template, request, send_file, url_for, current_app, send_from_directory
from flask_login import login_required
from io import BytesIO
from app.dao.common import get_doc_types
from app.dao.doc import get_docfiles_text, get_docfile_text, dbget_digfile_row
from app.main.doc import convert_html_to_pdf, get_docfile, get_docfiles, \
    docfile_create, upload_docfile, post_docfile, post_upload
from app.emails import app_send_email
import os

doc_bp = Blueprint('doc_bp', __name__)

@doc_bp.route('/docfile/<int:doc_id>', methods=['GET', 'POST'])
@login_required
def docfile(doc_id):
    if request.method == "POST":
        rent_id = post_docfile(doc_id)
        (url_for('rent_bp.rent', rent_id=rent_id))
    docfile, doc_dig = get_docfile(doc_id)
    doc_types = [typedoc.desc for typedoc in get_doc_types()]

    return render_template('docfile.html', docfile=docfile, doc_types=doc_types, doc_dig=doc_dig)


@doc_bp.route('/docfiles/<int:rent_id>', methods=['GET', 'POST'])
def docfiles(rent_id):
    docfiles, dfoutin = get_docfiles(rent_id)
    doc_types = [typedoc.desc for typedoc in get_doc_types()]
    outins = ["all", "out", "in"]

    return render_template('docfiles.html', rent_id=rent_id, dfoutin=dfoutin, docfiles=docfiles, doc_types=doc_types,
                           outins=outins)


@doc_bp.route('/docfiles_text/<int:rent_id>', methods=['GET', 'POST'])
def docfiles_text(rent_id):
    docfiles = get_docfiles_text(rent_id)

    return render_template('docfiles_text.html', docfiles=docfiles, rent_id=rent_id)


@doc_bp.route('/doc_print/<int:doc_id>', methods=['GET', 'POST'])
def doc_print(doc_id):
    try:
        docfile_text = get_docfile_text(doc_id)
        convert_html_to_pdf(docfile_text.doc_text, 'document.pdf')
        workingdir = os.path.abspath(os.getcwd())
        filepath = workingdir + '\\temp_files\\'
        return send_from_directory(filepath, 'document.pdf')
    except Exception as ex:
        message = f'Unable to produce document. Error: {str(ex)}'

        return redirect(url_for('doc_bp.docfiles', rent_id=0, message=message))


@doc_bp.route('/download/<int:doc_id>')
@login_required
def download(doc_id):
    digfile = dbget_digfile_row(doc_id)

    return send_file(BytesIO(digfile.dig_data), attachment_filename=digfile.summary, as_attachment=True,
                     mimetype='application/pdf')


@doc_bp.route('/email_and_save', methods=['POST'])
def email_and_save():
    if request.method == "POST":
        # create the record to be uploaded to `docfile` table
        # this contains the email
        docfile = docfile_create(0)
        # send the email now, from the docfile record
        appmail = current_app.extensions['mail']
        recipients = request.form.get('email_to')
        subject = request.form.get('email_subject')
        html_body = docfile.doc_text
        # next line will raise an exception if there is a problem actually sending the email
        app_send_email(appmail, recipients, subject, html_body)
        # now upload to the database
        upload_docfile(docfile)
        rent_id = docfile.rent_id

        return redirect(url_for('doc_bp.docfiles', rent_id=rent_id))


@doc_bp.route('/upload_file/<int:rent_id>', methods=["GET", "POST"])
@login_required
def upload_file(rent_id):
    rentcode = request.args.get('rentcode', "dummy", type=str)
    if request.method == "POST":
        post_upload()
        return redirect('/rent/{}'.format(rent_id))
    doc_types = [typedoc.desc for typedoc in get_doc_types()]
    return render_template('upload_dialog.html', doc_types=doc_types, rentcode=rentcode, rent_id=rent_id)

# @doc_bp.route('/uploads/<filename>')
# def upload(filename):
#     return send_from_directory(app.config['UPLOAD_PATH'], filename)

app/templates/mergedocs/PR.html
<!-- /templates/mergedocs/PR.html  -->
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% import 'widgets.html' as widgets %}
{% import 'mergedocs/PR_widgets.html' as pr_widgets with context%}

{% block app_content %}
<form method="POST" action="{{ url_for('pr_bp.pr_save_send', method=method, rent_id=rent_pr.id) }}">
    <div class="form-group row flex-row-reverse">
        <div class="col-md-3">
            <a href="{{ url_for('pr_bp.pr_dialog', rent_id=rent_pr.id, action='view') }}"
               class="btn btn-block btn-tog button-icon arrow-left" role="button">back to pr selection</a>
        </div>
        <div class="col-md-9">
            <span>Pay request preview | Choose address and edit the pay request below</span>
        </div>
    </div>
    <div class="row">
        <div class="col-md-9">
            <div id="address_fields" style="margin-bottom:1rem;">
                {{ widgets.combobox(name="address_fields", id="address_fields", items=[rent_pr.mailaddr,
                (rent_pr.tenantname + ', ' + rent_pr.propaddrs[0].propaddr),
                ('The owner/occupier, ' + rent_pr.propaddrs[0].propaddr)], item_selected=rent_pr.mailaddr) }}
            </div>
            <div id="doc_html" contenteditable="false">
                {% include 'mergedocs/PR_template.html' %}
            </div>
        </div>
        <div class="col-md-3">
            <div class="card card-white sticky-top">
                <div class="card-header">
                    <div class="row">
                        <div class="col"><span>Save and send this pay request</span>
                        </div>
                    </div>
                </div>
                <div class="card-body text-primary">
                    <div class="form-group row" style="margin-bottom:0px;">
                        <div class="col">
                            <button type="submit"
                                    formaction="{{ url_for('pr_bp.pr_save_send', method=2, rent_id=rent_pr.id) }}"
                                    class="btn btn-block btn-success save_pr button-icon letter" role="button">post
                            </button>
                            <button type="submit"
                                    formaction="{{ url_for('pr_bp.pr_save_send', method=3, rent_id=rent_pr.id) }}"
                                    class="btn btn-block btn-success save_pr button-icon mail-ic" role="button">post and
                                email
                            </button>
                            <button type="submit"
                                    formaction="{{ url_for('pr_bp.pr_save_send', method=1, rent_id=rent_pr.id) }}"
                                    class="btn btn-block btn-success save_pr button-icon email-ic" role="button">email
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <div class="col">
            <input type="hidden" id="pr_block" name="xinput" value="xyz">
            <input type="hidden" id="pr_addr" name="pr_addr" value="">
            <input type="hidden" id="pr_email_addr" name="pr_email_addr" value="{{ rent_pr.email if rent_pr.email
                        else 'example@gmail.com; example2@gmail.com'}}">
            <input type="hidden" id="pr_code" name="pr_code" value="{{ rent_pr.pr_code }}">
            <input type="hidden" id="rent_date" name="rent_date" value="{{ rent_pr.nextrentdate }}">
            <input type="hidden" id="tot_due" name="tot_due"
                   value="{{ rent_pr.rent_gale + rent_pr.arrears + rent_pr.totcharges }}">
            <input type="hidden" id="new_arrears_level" name="new_arrears_level"
                   value="{{ rent_pr.new_arrears_level }}">
            <input type="hidden" id="new_arrears" name="new_arrears" value="{{ rent_pr.arrears + rent_pr.rent_gale }}">
            <input type="hidden" id="charge_total" name="charge_total" value="{{ rent_pr.recovery_charge_amount }}">
            <input type="hidden" id="create_case" name="create_case" value="{{ rent_pr.create_case }}">
            <input type="hidden" id="pr_email" name="pr_email" value="{{ block_email }}">
        </div>
    </div>
</form>
{% endblock %}
{% block javascript %}
<script type="text/javascript">
    //copy address field and separate each line
    $('#address_fields').click(function() {
        var addr = $('#address_fields option:selected').text();
        var addr_split = addr.replace(/,/g, "<br />");
        $('#addr_span').html(addr_split);
        $('#addr_span').append("<br />");
    });
    //save pr - collect address to put in summary
    $('.save_pr').click(function() {
        var pr_block = $('#doc_html').html();
        $('#pr_block').val(pr_block);
        var pr_addr = $('#addr_span').text().trim();
        // remove unwanted characters
        var pr_addr_strip = pr_addr.replace(/[^\x20-\x7E]/gmi, "");
        // remove extra whitespace
        var pr_addr_strip_clean = pr_addr.replace(/\s+/g, " ");
        $('#pr_addr').val(pr_addr_strip_clean);
    });
</script>
{% endblock %}

app/templates/mergedocs/PRFS.html
<!DOCTYPE html>
<html>
<head>
	<link href="letters.css" rel="stylesheet" type="text/css">
</head>
<body>
	<!-- Payreq header -->

	<!-- %if %IsLetter% -->
	<!-- %include "payreq_header.html" -->
	<!-- %endif %IsLetter% -->

	<!-- %if %IsEmail% -->
	<!-- %include "email_header.html" -->
	<!-- %endif %IsEmail% -->

	<div class="font-size-medium" align="left">
		<!-- Subject -->
        <b>%Bold%</b>
        <br />

		<!-- Table of owings -->
		<!-- %include "payreq_table_forsale.html" -->
		
		<!-- Clauses -->
		<!-- %include "payreq_clauses_normal.html" -->

		<!-- %if %ChargeType% == "ground rent" % -->
        <br />
		<div class="font-size-small">
			Pursuant to Sections 47 and 48 of the Landlord & Tenant Act 1987, your Landlord is %Landlord% whose address (at which notices, including notices in proceedings, should be served) is %ManagerAddress%.
		</div>
		<!-- %endif %ChargeType% -->

		<br />
		This account is for %AccountSummary%. If you would like a receipt for a payment sent by post, please enclose a stamped envelope with your address on it.
		<br />
		<br />

		<!-- Payreq footer and remittance advice -->
		<!-- %include "payreq_footer_forsale.html" -->

		<!-- %if %IsEmail% -->
		<!-- %include "email_footer.html" -->
		<!-- %endif %IsEmail% -->
	</div>

	<!-- Include S166 here -->
	<!-- %if %IncludeS166% -->
	<!-- %include "s166.html" -->
	<!-- %endif -->
</body>
</html>

app/templates/mergedocs/PRX_template.html
{% import 'mergedocs/PR_widgets.html' as pr_widgets with context%}

<!-- font-size recognised by the pdf creation code -->
<style>
p
{
    font-size: 10.5pt;
}
</style>
<div id="manager_div" contenteditable="true">
    <div class="font-size-large manager-name" align="center" style="font-size:12.5pt;">
        <b>{{ rent_pr.landlord.manager.managername }}</b>
    </div>
    <div class="font-size-small manager-addr" align="center" style="font-size:9.5pt;">
        {{ rent_pr.landlord.manager.manageraddr }}
        <br/>
        {{ rent_pr.landlord.manager.manageraddr2 }}
        <br/>
    </div>
</div>
<div class="font-size-medium" align="right" contenteditable="true" style="font-size:10.5pt;">
    <span id="ref_span">Our Ref: {{ rent_pr.rentcode }}</span>
    <br/>
    Date: {{ today_date.strftime('%d-%b-%Y') }}
</div>
<div class="font-size-medium" align="left" style="font-size:10.5pt;">
					<span id="addr_span" class="block-text" contenteditable="true">
						{% set addr_list = rent_pr.mailaddr.split(',') %}
                        {% for item in addr_list %}
                            {{ item }}
                            <br/>
                        {% endfor %}
					</span>
    <br/>
    <br/>
    <b><span id="subject_span" class="block-text" contenteditable="true" style="font-size:10.5pt;">
						{{ capitalize_first_only(rent_pr.rent_type) }} account for property:
                        {% for addr in rent_pr.propaddrs %}
                            {{ addr.propaddr }}
                        {% endfor %}
					</span></b>
    <br/>
</div>
<div align="left" contenteditable="true">
    {{ pr_widgets.owings_table(rent_pr) }}
    <br>
    {% if rent_pr.suffix %}
    {{ pr_widgets.arrears_clause(rent_pr) }}
    {% endif %}
    <p>
        Please make your cheque/PO payable to {{ rent_pr.landlord.manager.managername }} with your reference
        {{ rent_pr.rentcode }} written on the back. If you prefer to pay us the {{
        money_str(rent_pr.rent_gale + rent_pr.arrears + rent_pr.totcharges, pound=True) }} by BACS or faster
        payments, our bank is {{ rent_pr.landlord.money_account.bank_name }}, our account is {{
        rent_pr.landlord.money_account.acc_name }}, the sort code is {{
        rent_pr.landlord.money_account.sort_code }} and our account number is {{
        rent_pr.landlord.money_account.acc_num }}. Please make sure that you give the property reference
        {{ rent_pr.rentcode }} with any BACS payment and please email us to confirm any BACS payment.
    </p>
    {{ pr_widgets.payment_advice(rent_pr) }}
    <br/>
    <br/>
    <p style="page-break-before: always"></p>
    {{ pr_widgets.pr_s166(rent_pr) }}
</div>

app/templates/mergedocs/PRXold.html
{% extends 'base.html' %}

{% block app_content %}
	<div contenteditable="true">
		<div class="font-size-large" align="center">
			<b>{{ rent.landlord.manager.managername }}</b>
		</div>
		<div class="font-size-small" align="center">
			{{ rent.landlord.manager.manageraddr }}
			<br />
			{{ rent.landlord.manager.manageraddr2 }}
			<br />
		</div>
		<div class="font-size-medium" align="right">
			Our Ref: {{ rent.rentcode }}
			<br />
			Date: {{ today_date }}
		</div>
		<div class="font-size-medium" align="left">
			<!-- Postal address -->
        	{% for item in mailaddr %}
				{{ item }}
				<br />
        	{% endfor %}
			<br />
			<br />
			<br />
			<br />
			<!-- Subject -->
			<b>{{ subject }}</b>
			<br />
			<br />
			<!-- Table of owings -->
			<!-- %include "payreq_table_normal.html" -->

			<!-- Clauses -->
			<!-- %include "payreq_clauses_normal.html" -->

			<!-- %if %ChargeType% == "ground rent" % -->
			{% if rent.tenuredet == "Rentcharge" %}
			<br />
			{% else %}
			<br />
			<div class="font-size-small">
				Pursuant to Sections 47 and 48 of the Landlord & Tenant Act 1987, your Landlord is {{ rent.landlord.name }} whose address (at which notices, including notices in proceedings, should be served) is {{ rent.landlord.manager.manageraddr }}.
			</div>
			{% endif %}
			<!-- %endif %ChargeType% -->

			<br />
			This account is for %AccountSummary%. If you would like a receipt for a payment sent by post, please enclose a stamped envelope with your address on it.
			<br />
			<br />

			<!-- Payreq footer and remittance advice -->
			<!-- Payreq footer normal -->
			<hr width="80%" />
			<div align="center">
				<b>PAYMENT ADVICE - %SendDate% - Ref: %RentCode%</b>
				<br />
				Please return this section with your payment
			</div>
			<br />
			Please find enclosed my/our cheque/PO for %TotalDue% to pay %AccountSummary%%ExtraRentStat% for property: %PropAddr%.
			<br />
			<!-- Include S166 here -->
			<!-- %if %IncludeS166% -->
			<!-- %include "s166.html" -->
			<!-- %endif -->
		</div>
	</div>
{% endblock %}

app/templates/mergedocs/PR_template.html
{% import 'mergedocs/PR_widgets.html' as pr_widgets with context%}
{% import 'widgets.html' as widgets %}
<!-- font-size recognised by the pdf creation code -->
<style>
p
{
    font-size: 10.5pt;
}
</style>
<div id="manager_div" contenteditable="true">
    <div class="font-size-large manager-name" align="center" style="font-size:12.5pt;">
        <b>{{ rent_pr.landlord.manager.managername }}</b>
    </div>
    <div class="font-size-small manager-addr" align="center" style="font-size:9.5pt;">
        {{ rent_pr.landlord.manager.manageraddr }}
        <br/>
        {{ rent_pr.landlord.manager.manageraddr2 }}
        <br/>
    </div>
</div>
<div class="font-size-medium" align="right" contenteditable="true" style="font-size:10.5pt;">
    <span id="ref_span">Our Ref: {{ rent_pr.rentcode }}</span>
    <br/>
    Date: {{ today_date.strftime('%d-%b-%Y') }}
</div>
<div class="font-size-medium" align="left" style="font-size:10.5pt;">
    <span id="addr_span" class="block-text" contenteditable="true">
        {% set addr_list = rent_pr.mailaddr.split(',') %}
        {% for item in addr_list %}
            {{ item }}
            <br/>
        {% endfor %}
    </span>
    <br/>
    <br/>
    <b><span id="subject_span" class="block-text" contenteditable="true" style="font-size:10.5pt;">
        {{ subject }}
    </span></b>
    <br/>
</div>
<div class="font-size-medium" align="left" contenteditable="true">
    {{ pr_widgets.owings_table(rent_pr) }}
    <p>
        {{ widgets.linebreaks_for_string(block) }}
    </p>
    {{ pr_widgets.payment_advice(rent_pr) }}
    <br/>
    <br/>
    <p style="page-break-before: always"></p>
    {{ pr_widgets.pr_s166(rent_pr) }}
</div>

app/templates/mergedocs/RECSTAX.html
<!-- /templates/mergedocs/RECSTAX.html  -->
{% extends 'base.html' %}
{% block app_content %}
<form method="POST" action="{{ url_for('doc_bp.email_and_save') }}">
	<div class="form-group row">
		<div class="col-md-1">
            <span>email to:</span>
        </div>
		<div class="col-md-6">
            <input type="text" class="form-control" id="email_to" name="email_to" value="{{ rent.email }}">
        </div>
	</div>
	<div class="form-group row">
		<div class="col-md-1">
            <span>subject:</span>
        </div>
		<div class="col-md-6">
            <input type="text" class="form-control" id="email_subject" name="email_subject" value="{{ subject }}">
        </div>
	</div>
    <div class="form-group row justify-content-end">
        <div class="col-md-3">
            <button id="savehtml" class="btn btn-block btn-success button-icon save">email and save</button>
        </div>
    </div>
    <div id="doc_html" contenteditable="true">
        {% if method == "letter" %}
        <div class="font-size-large" align="center">
            <b>{{ rent.landlord.manager.managername }}</b>
        </div>
        <div class="font-size-small" align="center">
            {{ rent.landlord.manager.manageraddr }}
            <br/>
            {{ rent.landlord.manager.manageraddr2 }}
            <br/>
        </div>
        <div class="font-size-medium" align="right">
            Our Ref: {{ rent.rentcode }}
            <br/>
            Date: {{ today_date.strftime('%d-%b-%Y') if today_date else 'none' }}
        </div>
        <div class="font-size-medium" align="left">
            {% for item in mailaddr %}
            {{ item }}
            <br/>
            {% endfor %}
            <br/>
            <br/>
            Dear {{ rent.tenantname }}
        </div>
        {% else %}
        <div class="font-size-medium" align="left">
            Our Ref: {{ rent.rentcode }}
            <br/>
            <br/>
            Email sent on {{ today_date.strftime('%d-%b-%Y') if today_date else 'none' }} to
            <span id="span_email_to">{{ rent.email }}</span>
            <br/>
            <br/>
            Dear {{ rent.tenantname }}
        </div>
        {% endif %}
        <div class="font-size-medium" align="left">
            <br/>
            <b><span id="span_email_subject">{{ subject }}</span></b>
            <br/>
            <br/>
            Thank you for your {{ variables.paytypedet }} payment in the sum of {{ variables.payamount }} received by
            us on {{ variables.paydate }} paying {{ variables.rent_type }} on the above property up
            to {{ rent.paidtodate.strftime('%d-%b-%Y') }}.
            <br/>
            <br/>
            {{ variables.rent_type.capitalize() }} on the above property will next be due and payable
            {{ rent.freqdet }} {{ rent.advarrdet }} on {{ rent.nextrentdate }} in the sum of {{ variables.rentgale }}.
            <br/>
            <br/>
            All Notices to the Lessor should be served only upon {{ rent.landlord.manager.managername }} at {{ rent.landlord.manager.manageraddr }}.
            <br/>
            <br/>
            Yours sincerely
            <br/>
            <br/>
            <br/>
            <b>{{ rent.landlord.manager.managername }}</b>
            {% if method == "email" %}
            <br/>
            <br/>
            {{ rent.landlord.manager.manageraddr }}
            <br/>
            <br/>
            {{ rent.landlord.manager.manageraddr2 }}
            <br/>
            {% endif %}
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-3">
            <input type="hidden" id="xinput" name="xinput" value="xyz">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-2">
            <input type="hidden" id="rent_id" name="rent_id" value="{{ rent.id }}">
        </div>
        <div class="col-md-2">
            <input type="hidden" id="rentcode" name="rentcode" value="{{ rent.rentcode }}">
        </div>
        <div class="col-md-2">
            <input type="hidden" id="doc_date" name="doc_date" value="{{ today_date }}">
        </div>
        <div class="col-md-2">
            <input type="hidden" id="summary" name="summary" value="{{ summary }}">
        </div>
        <div class="col-md-2">
            <input type="hidden" id="doc_type" name="doctype_id" value="{{ doctype_id }}">
        </div>
        <div class="col-md-2">
            <input type="hidden" id="out_in" name="out_in" value="out">
        </div>
    </div>
</form>
{% endblock %}
{% block javascript %}
<script type="text/javascript">
$(document).ready(function(){
    // copy "email_to" input into body
    $('#email_to').on("input", function() {
        $('#span_email_to').text($('#email_to').val());
    });
    // copy "email_subject" input into body
    $('#email_subject').on("input", function() {
        $('#span_email_subject').text($('#email_subject').val());
    });
});
</script>
{% endblock %}

app/templates/mergedocs/doc_in.html
{% extends 'base.html' %}

{% import 'widgets.html' as widgets %}

{% block app_content %}
<form method="POST" action="/save_html?item=doc_in">
    <div class="form-group row">
        <div class="col-md-3">
            <label for="rentcode">Rentcode:</label>
            <input type="text" id="rentcode" name="rentcode" value = "{{ rent_code }}">
        </div>
		<div class="col-md-3">
            <input type="hidden" id="xinput" name="xinput" value = "xyz">
        </div>
		<div class="col-md-3">
			<label for="doc_type">Type:</label>
			{{ widgets.combobox(name="doc_type", items=session['doc_types'], item_selected=session['doc_types'][0]) }}
		</div>
        <div class="col-md-3">
            <label for="doc_date">Date doc received:</label>
            <input type="date" class="form-control" name="doc_date"
                   value="{{ today_date }}">
        </div>
    </div>
	<div id="doc_html" contenteditable="true">
		<br />
		<br />
	</div>
    <div class="form-group row">
        <div class="col-md-3">
            <button id="savehtml" class="btn btn-block btn-success">Save doc_in as html</button>
        </div>
    </div>
</form>
{% endblock %}

app/templates/mergedocs/payreq_clauses_normal.html
<!-- Payreq clauses normal -->
<!-- Payreq clauses inserted with line breaks when present -->
<div class="font-size-medium" >
	<!-- %if %ClauseA% -->
	<br />
	%ClauseA%
	<br />
	<!-- %endif %ClauseA% -->

	<!-- %if %ClauseB% -->
	<br />
	%ClauseB%
	<br />
	<!-- %endif %ClauseB% -->

	<!-- %if %SpecialClause% -->
	<br />
	%SpecialClause%
	<br />
	<!-- %endif %SpecialClause% -->

	<!-- %if %ArrearsClause% -->
	<br />
	<b>%ArrearsClause%</b>
	<br />
	<!-- %endif %ArrearsClause% -->
</div>

app/templates/mergedocs/payreq_footer_forsale.html
<!-- Payreq footer for sale -->
<div class="font-size-medium" >
	<hr width = "80%" />
	<div align="center">
		<b>PAYMENT ADVICE - %SendDate% - Ref: %RentCode%</b>
		<br />
		Please return this section with your payment
	</div>
	<br />
	<form>
		<input type="checkbox"> Please find enclosed my/our cheque/PO for %TotalDue% to pay %AccountSummary%%ExtraRentStat% for %PropAddr%.
		<br>
		<br>
		<input type="checkbox"> I/We wish to purchase the %TenureType% interest in our property and enclose a cheque for %Price% made payable to %Manager% (please supply your FULL names and your telephone number below)
		<br />
		<br />
		<input type="checkbox"> I/We wish to purchase the %TenureType% interest in our property and enclose 6 post dated cheques, each for %PricePM% made payable to %Manager%, dated for the first day of each of the next 6 months. Please be sure to enclose all 6 signed and dated cheques with this form (please supply your FULL names and your telephone number below)
	</form>		
</div>

app/templates/mergedocs/payreq_footer_normal.html
<!-- Payreq footer normal -->
<div class="font-size-medium" >
	<hr width="80%" />
	<div align="center">
		<b>PAYMENT ADVICE - %SendDate% - Ref: %RentCode%</b>
		<br />
		Please return this section with your payment
	</div>
	<br />
	Please find enclosed my/our cheque/PO for %TotalDue% to pay %AccountSummary%%ExtraRentStat% for property: %PropAddr%.
	<br />
	<br />
</div>

app/templates/mergedocs/payreq_table_forsale.html
<!-- Payreq table of owings for sale -->
<div align="left" >
	<br />
	<table class="font-size-medium" width="100%" border="1" cellspacing="0" cellpadding="2">
		<!-- Jinn to insert these rows (if they exist) -->
		%RentTable%
		%ArrearsTable%
		%ChargesTable%
		<tr>
			<td>
				<b>The total amount payable is:</b>
			</td>
			<td align="right">
				<b>%TotalDue%</b>
			</td>
		</tr>
		<tr>
			<td> <strong> Alternatively, purchase your %TenureType% </strong> - There are many advantages to be gained by buying out your %TenureType%. In many cases, a householder cannot insure, extend or alter without the consent of the %TenureType% owner, which can sometimes involve significant costs. If you purchase your %TenureType% from us, such restrictions will no longer apply. Our all inclusive price, to include all our legal costs and a final adjustment for rent (overpaid or underpaid as appropriate) is shown on the right. There is nothing further to pay. This quotation is valid for 35 days.
			</td>
			<td align="right">
				<b>%Price%</b>
			</td>
		</tr>
	</table>
</div>

app/templates/mergedocs/payreq_table_normal.html
<!-- Payreq table of owings normal  -->
<div align="left" >
	<br />
	<table class="font-size-medium" width="100%" border="1" cellspacing="0" cellpadding="2">
		<!-- Jinn to insert these rows (if they exist) -->
		%RentTable%
		%ArrearsTable%
		%ChargesTable%
		<tr>
			<td>
				<b>The total amount payable is:</b>
			</td>
			<td align="right">
				<b>%TotalDue%</b>
			</td>
		</tr>
	</table>
</div>