app/views/agent.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import login_required
from app.main.agent import delete_agent, delete_agent_headrent, mget_agents_from_recent, mget_agents_from_search, \
    prepare_agent_template, select_new_agent, \
    update_agent, unlink_agent_from_rent
from app import db
agent_bp = Blueprint('agent_bp', __name__)


@agent_bp.route('/agent/<int:agent_id>', methods=["GET", "POST"])
@login_required
# TODO: Refector so that we are not using '0' as a value for any ids.
def agent(agent_id):
    headrent_id = request.args.get('headrent_id', type=int)
    rent_id = request.args.get('rent_id', type=int)
    rentcode = request.args.get('rentcode', "ABC1", type=str)
    action = request.args.get('action', type=str)
    if request.method == "POST":
        try:
            agent_id, message = update_agent(agent_id, rent_id)
        except Exception as ex:
            message = f"Update agent failed. Database rolled back. Error:  {str(ex)}"
            db.session.rollback()
        if rent_id != 0:
            return redirect(url_for('rent_bp.rent', rent_id=rent_id, message=message))
    agent, rents, headrents = prepare_agent_template(agent_id)
    return render_template('agent.html', action=action, agent=agent, headrent_id=headrent_id, rent_id=rent_id,
                           rentcode=rentcode, rents=rents, headrents=headrents)


@agent_bp.route('/agent_delete/<int:agent_id>', methods=["GET", "POST"])
@login_required
def agent_delete(agent_id):
    if request.method == "POST":
        rent_id = request.args.get('rent_id', 0, type=int)
        headrent_id = request.args.get('headrent_id', 0, type=int)
        try:
            message = delete_agent(agent_id, rent_id) if headrent_id == 0 else delete_agent_headrent(agent_id, headrent_id)
        except Exception as ex:
            message = f"Agent delete failed. Database rolled back. Error: {str(ex)}"
            db.session.rollback()
        if rent_id == 0:
            return redirect(url_for('agent_bp.agents', message=message))
        else:
            return redirect(url_for('rent_bp.rent', rent_id=rent_id, message=message))


@agent_bp.route('/agent_unlink/<int:rent_id>', methods=["GET", "POST"])
@login_required
def agent_unlink(rent_id):
    if request.method == "POST":
        try:
            message = unlink_agent_from_rent(rent_id)
        except Exception as ex:
            message = f"Agent unlink failed. Database rolled back. Error:  {str(ex)}"
            db.session.rollback()
        return redirect(url_for('rent_bp.rent', rent_id=rent_id, message=message))


@agent_bp.route('/agents', methods=['GET', 'POST'])
@login_required
def agents():
    rent_id = request.args.get('rent_id', 0, type=int)
    rentcode = request.args.get('rentcode', "ABC1", type=str)
    agent_id = request.args.get('agent_id', 0, type=int)
    fdict = {}
    if request.method == 'POST':
        agents, fdict = mget_agents_from_search()
    else:
        agents = mget_agents_from_recent()
    return render_template('agents.html', agents=agents, agent_id=agent_id, fdict=fdict, rent_id=rent_id,
                           rentcode=rentcode)


@agent_bp.route('/agents_select', methods=['GET', 'POST'])
@login_required
def agents_select():
    rent_id = request.args.get('rent_id', type=int)
    agent_id = request.args.get('agent_id', type=int)
    try:
        message = select_new_agent(agent_id, rent_id)
    except Exception as ex:
        message = f'Unable to update rent table with new agent link. Database rolled back. Error: {str(ex)}'
        db.session.rollback()
    return redirect(url_for('rent_bp.rent', rent_id=rent_id, message=message))

app/views/charge.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import login_required
from app.dao.charge import post_charge
from app.main.charge import mget_charge, mget_charges

charge_bp = Blueprint('charge_bp', __name__)


@charge_bp.route('/charge/<int:charge_id>', methods=["GET", "POST"])
@login_required
def charge(charge_id):
    if request.method == "POST":
        rent_id = post_charge(charge_id)

        return redirect(url_for('rent_bp.rent', rent_id=rent_id))

    charge, chargedescs = mget_charge(charge_id)

    return render_template('charge.html', charge=charge, chargedescs=chargedescs)


@charge_bp.route('/charges', methods=['GET', 'POST'])
def charges():
    rent_id = request.args.get('rent_id', "0", type=str)
    rentcode = request.args.get('rentcode', "", type=str)
    charges = mget_charges(rent_id)

    return render_template('charges.html', charges=charges, rent_id=rent_id, rentcode=rentcode)

app/views/income.py
from flask import Blueprint, render_template, request
from flask_login import login_required
from app.dao.income import get_income_, post_income_
from app.main.income import get_income_dict, get_incomes

income_bp = Blueprint('income_bp', __name__)


@income_bp.route('/income/<int:acc_id>', methods=['GET', 'POST'])
def income(acc_id):
    # display recent income postings for money account id or (if 0) for all accounts
    # if rent_id is passed it will be interpreted in the following get
    incomes, incomevals = get_incomes(acc_id)
    income_dict = get_income_dict("basic")

    return render_template('income.html', income_dict=income_dict, incomes=incomes, incomevals=incomevals)


@income_bp.route('/income_item/<int:income_id>', methods=['GET', 'POST'])
@login_required
def income_item(income_id):
    # action = request.args.get('action', "view", type=str)
    if request.method == "POST":
        income_id = post_income_(income_id)

    income_dict = get_income_dict("enhanced")
    income, incomeallocs = get_income_(income_id)

    return render_template('income_item.html', income=income, incomeallocs=incomeallocs,
                           income_dict=income_dict)

app/views/income_.py
from flask import Blueprint, render_template, redirect, request
from flask_login import login_required
from app.dao.income_ import get_income_dict, get_income_, get_incomes, post_income_

income_bp = Blueprint('income_bp', __name__)

@income_bp.route('/income/<int:acc_id>', methods=['GET', 'POST'])
def income(acc_id):
    # display recent income postings for money account id or (if 0) for all accounts
    # if rent_id is passed it will be interpreted in the following get
    incomes, incomevals = get_incomes(acc_id)
    income_dict = get_income_dict("basic")

    return render_template('income.html', income_dict=income_dict, incomes=incomes, incomevals=incomevals)

@income_bp.route('/income_item/<int:income_id>', methods=['GET', 'POST'])
@login_required
def income_item(income_id):
    # action = request.args.get('action', "view", type=str)
    if request.method == "POST":
        income_id = post_income_(income_id)

    income_dict = get_income_dict("enhanced")
    income, incomeallocs = get_income_(income_id)

    return render_template('income_item.html', income=income, incomeallocs=incomeallocs,
                           income_dict=income_dict)

app/views/loan.py
from flask import Blueprint, render_template, request
from flask_login import login_required
from app.main.loan import get_loan, get_loans, get_loan_stat

loan_bp = Blueprint('loan_bp', __name__)


@loan_bp.route('/loan/<int:loan_id>', methods=['GET', 'POST'])
@login_required
def loan(loan_id):
    loan = get_loan(loan_id)

    return render_template('loan.html', loan=loan)


@loan_bp.route('/loans', methods=['GET', 'POST'])
def loans():
    action = request.args.get('action', "view", type=str)
    loans, loansum = get_loans(action)

    return render_template('loans.html', loans=loans, loansum=loansum)


@loan_bp.route('/loanstat_dialog/<int:loan_id>', methods=["GET", "POST"])
def loanstat_dialog(loan_id):
    code = request.args.get('code', "ABC-123", type=str)

    return render_template('loanstat_dialog.html', code=code, loanid=loan_id)


@loan_bp.route('/loan_statement/<int:loan_id>', methods=["GET", "POST"])
@login_required
def loan_statement(loan_id):
    checksums, loancode, loanstatement = get_loan_stat(loan_id)

    return render_template('loan_stat.html', checksums=checksums, loancode=loancode, loanstatement=loanstatement)

app/views/money.py
from flask import Blueprint, redirect, render_template,  request, url_for
from flask_login import login_required
from app.dao.money import get_money_acc, get_moneydets, get_moneydict, \
    get_money_item, get_money_items, post_money_acc, post_money_acc_new, post_money_item
from app import db

money_bp = Blueprint('money_bp', __name__)


@money_bp.route('/money', methods=['GET', 'POST'])
def money():
    message = request.args.get('message')
    accsums, moneydets = get_moneydets()

    return render_template('money.html', accsums=accsums, moneydets=moneydets, message=message)


@money_bp.route('/money_acc/<int:acc_id>', methods=['GET', 'POST'])
@login_required
def money_acc(acc_id):
    message = request.args.get('message')
    if request.method == "POST":
        try:
            acc_id = post_money_acc(acc_id)
        except Exception as ex:
            message = f"Error posting new money account. Database rolled back. Error: {str(ex)}"
            db.sesssion.rollback()
        return redirect(url_for('money_bp.money_acc', acc_id=acc_id, message=message))
    moneyacc = get_money_acc(acc_id)

    return render_template('money_acc.html', moneyacc=moneyacc, message=message)


@money_bp.route('/money_acc_new', methods=['GET', 'POST'])
@login_required
def money_acc_new():
    if request.method == "POST":
        try:
            acc_id = post_money_acc_new()
            message = 'New account created successfully.'
            return redirect(url_for('money_bp.money', acc_id=acc_id, message=message))
        except Exception as ex:
            message = f"Error posting new money account. Database rolled back. Error: {str(ex)}"
            db.sesssion.rollback()
            return redirect(url_for('money_bp.money', message=message))
    return render_template('money_acc.html')


@money_bp.route('/money_deduce/<int:item_id>/<mode>', methods=['GET', 'POST'])
def money_deduce(item_id, mode='Y'):    #determines if table item is income or money - clunky and horrible
    # mode = request.args.get('mode', "X", type=str)
    if mode == "X":
        return redirect(url_for('income_bp.income_item', income_id=item_id))
    else:
        return redirect(url_for('money_bp.money_item', money_item_id=item_id))


@money_bp.route('/money_item/<int:money_item_id>', methods=['GET', 'POST'])
def money_item(money_item_id):
    if request.method == "POST":
        money_item_id = post_money_item(money_item_id)
        return redirect(url_for('money_bp.money_item', money_item_id=money_item_id))
    money_dict = get_moneydict()
    money_item, cleared = get_money_item(money_item_id)

    return render_template('money_item.html', cleared=cleared, money_dict=money_dict, money_item=money_item)


@money_bp.route('/money_items/<int:acc_id>', methods=["GET", "POST"])
@login_required
def money_items(acc_id):  # if account id is 0 show items for all accounts
    # post values are filter values, so dealt with in the following get function
    accsums, moneyvals, transitems = get_money_items(acc_id)
    money_dict = get_moneydict("plus_all")

    return render_template('money_items.html', accsums=accsums, money_dict=money_dict, moneyvals=moneyvals,
                           transitems=transitems)

app/views/rent.py
from flask import Blueprint, render_template, redirect, request, url_for
from flask_login import login_required
from app import db
from app.dao.common import get_filters
from app.dao.rent import delete_rent_filter, get_rent_external
from app.main.common import get_combodict_rent, mpost_search
from app.main.rent import collect_rents_advanced_html_elements, get_rentp, mget_recent_searches, get_rents_basic_sql, \
    mget_rents_errors_list, get_rents_external, rent_validation, update_landlord, update_rent_rem, \
    update_tenant, mpost_rent_filter, mget_rents_advanced, mget_rents_advanced_from_search
from app.main.rent_filter import dict_advanced
rent_bp = Blueprint('rent_bp', __name__)


@rent_bp.route('/delete_filter<int:item_id>', methods=['GET', 'POST'])
def delete_filter(item_id):
    method = request.args.get('method')
    delete_rent_filter(item_id)
    if method == 'payrequest':
        return redirect(url_for('pr_bp.pr_start'))
    else:
        return redirect(url_for('rent_bp.rents_advanced', filtr_id=0, method=method))


@rent_bp.route('/load_filter', methods=['GET', 'POST'])
def load_filter():
    # load predefined filters from jstore for filter
    jfilters = get_filters(2)

    return render_template('load_filter.html', jfilters=jfilters)


@rent_bp.route('/rent/<int:rent_id>', methods=['GET', 'POST'])
# @login_required
def rent(rent_id):
    nav = request.args.get('nav', '', type=str)
    nav_id = request.args.get('nav_id', 0, type=int)
    message = request.args.get('message', '', type=str)
    combodict = get_combodict_rent()
    # gather rent combobox values
    rent = get_rentp(rent_id) if rent_id != 0 else {"id": 0}    # get full enhanced rent pack
    # basic validation check for mail and email variables
    messages = rent_validation(rent, message)

    return render_template('rent.html', rent=rent, combodict=combodict, messages=messages, nav=nav, nav_id=nav_id)


@rent_bp.route('/rent_external/<int:rent_external_id>', methods=["GET"])
@login_required
def rent_external(rent_external_id):  # view external rent from home rents page
    rent_external = get_rent_external(rent_external_id)

    return render_template('rent_external.html', rent_external=rent_external)


@rent_bp.route('/rents_advanced/<int:filtr_id>', methods=['GET', 'POST'])
@login_required
def rents_advanced(filtr_id):  # get rents for advanced queries page and pr page
    message = request.args.get('message', '', type=str)
    action = request.args.get('action', 'query', type=str)
    method = request.args.get('method', 'rent', type=str)
    rents = []
    if request.method == 'POST':
        if action == 'save':
            try:
                filtr_id = mpost_rent_filter()
                message = "Filter saved successfully."
            except Exception as ex:
                message = f"Unable to save filter. Database rolled back. Error: {str(ex)}"
                db.sesssion.rollback()
            return redirect(url_for('rent_bp.rents_advanced', filtr_id=filtr_id, action='load', method=method,
                                    message=message))
        else:
            fdict, rents = mget_rents_advanced_from_search()
    if action == 'load':
        fdict, rents = mget_rents_advanced(filtr_id)
    else:
        fdict = dict_advanced()
    rents, are_errors = mget_rents_errors_list(rents)
    combodict, fdict, jfilters, pr_defaults, pr_template_codes = collect_rents_advanced_html_elements(fdict, method)
    return render_template('rents_advanced.html', action=action, combodict=combodict, filtr_id=filtr_id,
                           fdict=fdict, jfilters=jfilters, method=method, pr_defaults=pr_defaults,
                           pr_template_codes=pr_template_codes, rents=rents, are_errors=are_errors,
                           message=message)


@rent_bp.route('/', methods=['GET', 'POST'])
@rent_bp.route('/rents_basic', methods=['GET', 'POST'])
@login_required
def rents_basic():  # get rents_basic for home rents_basic page with simple search option
    fdict, rents = get_rents_basic_sql()
    if request.method == "POST":
        # We save the search if it is not already in the recent_search table and if there are values in the dictionary
        if not all(value == '' for value in fdict.values()):
            mpost_search(fdict, 'rent')
    recent_searches = mget_recent_searches('rent')
    return render_template('rents_basic.html', fdict=fdict, rents=rents, recent_searches=recent_searches)


@rent_bp.route('/rents_external', methods=['GET', 'POST'])
@login_required
def rents_external():  # get external rents for home rents page with simple search option
    fdict, rents = get_rents_external()

    return render_template('rents_external.html', fdict=fdict, rents=rents)


@rent_bp.route('/tenant/<int:rent_id>', methods=['GET', 'POST'])
# @login_required
def tenant(rent_id):    # update tenant details from rent page
    update_tenant(rent_id)

    return redirect(url_for('rent_bp.rent', rent_id=rent_id))


# update rent details from rent page based on action (from tenant/landlord/edit_rent modal)
@rent_bp.route('/rent_update/<int:rent_id>', methods=['GET', 'POST'])
# @login_required
def rent_update(rent_id):
    action = request.args.get('action', type=str)
    message = ''
    try:
        if action == 'landlord':
            update_landlord(rent_id)
        elif action == 'tenant':
            update_tenant(rent_id)
        elif action == 'rent':
            update_rent_rem(rent_id)
    except Exception as ex:
        message = f"Update rent failed. Database rolled back. Error:  {str(ex)}"
        db.session.rollback()
    return redirect(url_for('rent_bp.rent', rent_id=rent_id, message=message))

app/views/utilities.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import login_required
from app.dao.delete import delete_record
from app.dao.functions import backup_database

ut_bp = Blueprint('ut_bp', __name__)

@ut_bp.route('/backup', methods=['GET', 'POST'])
# @login_required
def backup():
    if request.method == "POST":
        backup_database()

    return render_template('backup.html')

@ut_bp.route('/delete_item/<int:id>')
@login_required
def delete_item(id):
    redir, rentid = delete_record(id)

    return redirect(url_for('{}'.format(redir)))

app/templates/deeds.html
<!-- /templates/agents.html  -->
{% extends 'base.html' %}

{% block app_content %}
<div class="table-fixed">
    <table class="table" id="deeds">
        <thead>
        <tr>
            <th style="width: 15.00%">deed code</th>
            <th style="width: 20.00%">our notice fee</th>
            <th style="width: 30.00%">deed notice fee</th>
            <th style="width: 30.00%">deetails</th>
            <th style="width: 5.00%">action</th>
        </tr>
        </thead>
        <tbody>
        {% for item in deeds %}
        <tr id="{{ item.id }}">
            <td style="width: 15.00%">{{ item.deedcode }}</td>
            <td style="width: 20.00%">{{ item.nfee }}</td>
            <td style="width: 30.00%"> {{ item.nfeeindeed }}</td>
            <td style="width: 30.00%"> {{ item.info }}</td>
            <td style="width: 5.00%" class="vertical-align"><a href="{{ url_for('util_bp.deed', deed_id=item.id) }}"
                                       class="btn btn-primary btn-small button-icon eye" role="button">view</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

app/templates/loans.html
<!-- /templates/loans.html  -->
{% extends 'base.html' %}

{% block app_content %}
<form method="POST" id="target">
    <div class="form-group row flex-row-reverse">
        <div class="col-md-3">
            <a href="{{ url_for('loan_bp.loan', loan_id=0) }}"
               class="btn btn-block btn-danger button-icon plus" role="button">add new loan</a>
        </div>
        <div class="col-md-3">
            <a href="{{ url_for('loan_bp.loans', action='Nick') }}"
               class="btn btn-block btn-primary button-icon filter" role="button">show only Nick loans</a>
        </div>
    </div>
</form>
<div class="table-fixed">
    <table class="table" id="loans">
        <thead>
        <tr>
            <th style="width: 10.00%">code</th>
            <th style="width: 22.00%">borrower</th>
            <th style="width: 8.00%">int rate</th>
            <th style="width: 12.00%">lender</th>
            <th style="width: 12.00%">end date</th>
            <th style="width: 12.00%">notes</th>
            <th style="width: 12.00%">valuation date</th>
            <th style="width: 10.00%">valuation</th>
            <th style="width: 2.00%"></th>
        </tr>
        </thead>
        <tbody>
        {% for item in loans %}
        <tr id="{{ item.id }}">
            <td style="width: 10.00%">{{ item.code }}</td>
            <td style="width: 22.00%"> {{ item.borrower }}</td>
            <td style="width: 8.00%"> {{ item.interest_rate }}</td>
            <td style="width: 12.00%"> {{ item.lender }}</td>
            <td style="width: 12.00%"> {{ item.end_date.strftime('%d-%b-%Y') if item.end_date else 'none'  }}</td>
            <td style="width: 12.00%"> {{ item.notes }}</td>
            <td style="width: 12.00%"> {{ item.val_date.strftime('%d-%b-%Y') if item.val_date else 'none'  }}</td>
            <td style="width: 8.00%"> {{ item.valuation }}</td>
            <td style="width: 2.00%" class="vertical-align"><a href="{{ url_for('loan_bp.loan',
            loan_id=item.id) }}" class="btn btn-teal-light btn-round button-icon round circles" role="button"></a>
        </tr>
        {% endfor %}
        <tr>
        </tr>
        <tr>

        </tr>
        </tbody>
    </table>
    <table class="table table-base">
        <thead>
        <tr>
            <td style="width: 10.00%"></td>
            <td style="width: 25.00%">total of loan valuations</td>
            <td style="width: 15.00%"> {{ loansum.totval }} </td>
            <td style="width: 25.00%">total of loan annual interest</td>
            <td style="width: 15.00%"> {{ loansum.totint }} </td>
            <td style="width: 10.00%"></td>
        </tr>
        </thead>
    </table>
</div>
{% endblock %}

app/templates/money_item.html
<!-- /templates/money_item.html  -->
{% extends 'base.html' %}

{% import 'widgets.html' as widgets %}

{% block app_content %}
<form method="POST" id="money_item">
    <div class="form-group row flex-row-reverse">
        <div class="col-md-3">
            <a href="{{ url_for('money_bp.money_items', acc_id=money_item.acc_id) }}"
               class="btn btn-block btn-tog button-icon arrow-left" role="button">back to items</a>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-3">
            <label for="paydate">pay date:</label>
            <input type="date" class="form-control" name="paydate" value="{{ money_item.date }}" readonly="true">
        </div>
        <div class="col-md-2">
            <label for="amount">total:</label>
            <input type="text" class="form-control" name="amount" value="{{ money_item.amount }}" readonly="true">
        </div>
        <div class="col-md-3">
            <label for="payer">payer:</label>
            <input type="text" class="form-control" name="payer" value="{{ money_item.payer }}" readonly="true">
        </div>
        <div class="col-md-2">
            <label for="number">number:</label>
            <input type="text" class="form-control" name="number" value="{{ money_item.num }}" readonly="true">
        </div>
        <div class="col-md-2">
            <label for="cleared">cleared:</label>
            {{ widgets.combobox(name="cleared", items=money_dict.cleareds, item_selected=cleared) }}
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-6">
            <label for="memo">memo:</label>
            <input type="text" class="form-control" name="memo" value="" readonly="true">
        </div>
        <div class="col-md-3">
            <label for="category">category:</label>
            {{ widgets.combobox(name="category", items=money_dict.cats, item_selected=money_item.cat_name) }}
        </div>
        <div class="col-md-3">
            <label for="acc_desc">bank account:</label>
            {{ widgets.combobox(name="acc_desc", items=money_dict.acc_descs, item_selected=money_item.acc_desc) }}
        </div>
    </div>
    <div class="form-group row flex-row-reverse">
        <div class="col-md-2">
            <button type="button" id="edit_view" class="btn btn-block btn-secondary button-icon edit">edit</button>
        </div>
    </div>
    <div class="form-group row flex-row-reverse" id="save_delete" >
        <div class="col-md-2">
            <button type="submit" class="btn btn-block btn-success button-icon save">save changes</button>
        </div>
        <div class="col-md-2">
            <button type="submit" formaction="{{ url_for('money_bp.money_item', money_item_id=0) }}"
                    class="btn btn-block btn-success button-icon save">save as new item</button>
        </div>
        <div class="col-md-2">
            <a href="{{ url_for('util_bp.delete_item', item_id=money_item.id,
            item='momey_item', id_2=money_item.acc_id) }}"
               onclick="return confirm('Are you sure you want to delete this transaction?');"
               class="btn btn-block btn-warning button-icon trash" role="button">delete transaction</a>
        </div>
    </div>
</form>
{% endblock %}

app/templates/rents_external.html
<!-- /templates/rents_external.html  -->
{% extends 'base.html' %}

{% block app_content %}
<form method="POST" id="target">
    <div class="form-group row">
        <div class="col-md-2">
            <label for="rentcode">rentcode starts with:</label>
            <input type="text" class="form-control" name="rentcode" placeholder="any"
                   value="{{ fdict.rentcode }}">
        </div>
        <div class="col-md-2">
            <label for="tenantname">tenant name:</label>
            <input type="text" class="form-control" name="tenantname" placeholder="any"
                   value="{{ fdict.tenantname }}">
        </div>
        <div class="col-md-2">
            <label for="propaddr">property details:</label>
            <input type="text" class="form-control" name="propaddr" placeholder="any"
                   value="{{ fdict.propaddr }}">
        </div>
        <div class="col-md-2">
            <label for="source">source:</label>
            <input type="text" class="form-control" name="source" placeholder="any" value="{{ fdict.source }}">
        </div>
        <div class="col-md-2">
            <label for="agentdetail">agent details:</label>
            <input type="text" class="form-control" name="agentdetail" placeholder="any"
                   value="{{ fdict.agentdetail }}">
        </div>
        <div class="col-md-2">
            <label for="count">count:</label>
            <input type="text" class="form-control" name="count" value="{{ rent_s|length }}">
        </div>
    </div>
    <div class="form-group row flex-row-reverse">
        <div class="col-md-3">
            <button type="submit" class="btn btn-block btn-success  button-icon search" role="button">search</button>
        </div>
        <div class="col-md-3">
            <button type="submit" formaction="{{ url_for('rent_bp.rents_basic') }}"
                    class="btn btn-block btn-success  button-icon search" role="button">search main</button>
        </div>
    </div>
</form>
<!--<div class="container">-->
<!--    <div class="row voffset2">-->
<!--        <div class="col-lg-12">-->
<!--            <h4 class="text-center">Filter name: {{ jname }}</h4>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<div class="table-fixed">
    <table class="table" id="externalrents">
        <thead>
        <tr>
            <th style="width: 8.00%">rentcode</th>
            <th style="width: 8.00%">rentpa</th>
            <th style="width: 8.00%">arrears</th>
            <th style="width: 8.00%">lastrentdate</th>
            <th style="width: 15.00%">tenantname</th>
            <th style="width: 18.00%">propaddr</th>
            <th style="width: 8.00%">source</th>
            <th style="width: 18.00%">agent details</th>
            <th style="width: 9.00%"></th>
        </tr>
        </thead>
        <tbody>
        {% for item in rents %}
        <tr id="{{ item.id }}">
            <td style="width: 8.00%">{{ item.rentcode }}</td>
            <td style="width: 8.00%"> {{ item.rentpa }}</td>
            <td style="width: 8.00%"> {{ item.arrears }}</td>
            <td style="width: 8.00%"> {{ item.lastrentdate.strftime('%d-%b-%Y') if item.lastrentdate else 'none' }}</td>
            <td style="width: 15.00%"> {{ item.tenantname }}</td>
            <td style="width: 18.00%">{{ item.propaddr }}</td>
            <td style="width: 8.00%"> {{ item.source }}</td>
            <td style="width: 18.00%"> {{ item.agentdetail }}</td>
            <td style="width: 9.00%" class="vertical-align"><a href="{{ url_for('rent_bp.rent_external', rent_external_id=item.id) }}"
                                        class="btn btn-teal-light btn-round button-icon round circles" role="button"></a>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}